### ISSUE TITLE
My TennisBot doesn't work

### ISSUE THREAD

**Issue by carycheng** [sujaygarlanka/AutoBot#1]
I tried to play tennis at ten-ish with my TennisBot but it just sat there idly with seemingly no efforts nor interests. Make me wonder how dedicated TennisBot is to its craft.

**Comment by carycheng** [comment]
@sujaygarlanka please fix

**Comment by sujaygarlanka** [comment]
@carycheng Have you tried a hard reset? If that doesn’t work, try speaking to it kindly with phrases like “You can do it!”, “Believe in yourself!”, or “Every journey of a thousand miles starts with a single step.”. TennisBot responds well to encouragement and positive reinforcement. If that still doesn’t work, please visit our website and speak with our ChatBot. Thanks!

**Comment by carycheng** [comment]
I see that you preemptively closed this issue before I was able to test. I also just chatted with ChatBot and it seemed equally nonchalant and requested I filed a ticket with TicketBot.

Reopening for visibility in case anyone else runs into this
